"""Type stubs for the wasm3._wasm3 extension - hand-written, update alongside _wasm3.c."""

from collections.abc import Callable
from typing import Any, overload

from typing_extensions import Buffer  # collections.abc.Buffer is 3.12+; stubs are never imported

M3_VERSION: str

WasmValue = int | float

class Environment:
    def __init__(self) -> None: ...
    def new_runtime(self, stack_size_bytes: int, /) -> Runtime: ...
    # Binary modules only. wasm3.Environment subclasses this and also takes the text
    # format, assembling it with the bundled wabt build first.
    def parse_module(self, data: bytes, /) -> Module: ...

class Runtime:
    # Native gas metering. Bodies are instrumented as they compile, so set gas_limit before
    # find_function(); setting it re-arms the full budget, 0 disables. Running out raises
    # RuntimeError("[trap] out of gas").
    gas_limit: float
    @property
    def gas_used(self) -> float: ...
    def load(self, module: Module, /) -> None: ...
    def find_function(self, name: str, /) -> Function: ...

    # Suspendable execution. The pause points are compiled in, so set suspendable before
    # find_function(), like gas_limit. A call that pauses returns None with `suspended`
    # set; resume() continues it and returns its results, or None if it paused again.
    # A request pauses at the next loop back edge or function entry - the next call's,
    # if the running one reaches none. Running out of gas requests a pause instead of
    # trapping: set gas_limit again before resume() to refill the budget.
    suspendable: bool
    @property
    def suspended(self) -> bool: ...
    def request_suspend(self) -> None: ...
    def resume(self) -> Any: ...
    # The paused call, its module's memories, globals and tables, in wasm3's portable
    # format (with nothing paused, a postmortem of the last call, which cannot resume).
    def save_snapshot(self) -> bytes: ...
    # Into a module loaded into this runtime, linked, with none of its code run yet.
    # Afterwards, resume() continues the call the snapshot was taken of.
    def load_snapshot(self, module: Module, data: Buffer, /) -> None: ...

class Module:
    @property
    def name(self) -> str: ...
    # Legacy: only counts modules pre-instrumented with ewasm's metering.usegas import.
    gasLimit: float
    @property
    def gasUsed(self) -> float: ...
    @overload
    def link_function(self, module: str, name: str, function: Callable[..., Any], /) -> None: ...
    @overload
    def link_function(self, module: str, name: str, signature: str, function: Callable[..., Any], /) -> None: ...
    def link_global(self, module: str, name: str, value: WasmValue, /) -> None: ...
    def get_global(self, name: str, /) -> WasmValue: ...
    def set_global(self, name: str, value: WasmValue, /) -> None: ...
    # By index, or by export name ("memory"). Raises RuntimeError when there is no such
    # memory, or before the module is loaded.
    def get_memory(self, key: int | str = 0, /) -> Memory: ...

class Memory:
    """A module's linear memory, looked up afresh on every access - safe to keep across memory.grow.

    Slices are copies; write back with slice assignment. memoryview(mem) is zero-copy, but
    dangles once the memory grows.
    """

    def __len__(self) -> int: ...
    @overload
    def __getitem__(self, key: int, /) -> int: ...
    @overload
    def __getitem__(self, key: slice, /) -> bytes: ...
    @overload
    def __setitem__(self, key: int, value: int, /) -> None: ...
    @overload
    def __setitem__(self, key: slice, value: Buffer, /) -> None: ...
    def __buffer__(self, flags: int, /) -> memoryview: ...

class Function:
    @property
    def name(self) -> str: ...
    @property
    def num_args(self) -> int: ...
    @property
    def num_rets(self) -> int: ...
    # wasm3's M3ValueType: 1=i32, 2=i64, 3=f32, 4=f64.
    @property
    def arg_types(self) -> tuple[int, ...]: ...
    @property
    def ret_types(self) -> tuple[int, ...]: ...
    def call_argv(self, *args: str) -> Any: ...
    def __call__(self, *args: WasmValue) -> Any: ...
