"""Type stubs for the wasm3._wasm3 extension - hand-written, update alongside _wasm3.c."""

from collections.abc import Callable
from typing import Any, overload

M3_VERSION: str

WasmValue = int | float

class Environment:
    def __init__(self) -> None: ...
    def new_runtime(self, stack_size_bytes: int, /) -> Runtime: ...
    def parse_module(self, data: bytes, /) -> Module: ...

class Runtime:
    def load(self, module: Module, /) -> None: ...
    def find_function(self, name: str, /) -> Function: ...
    def get_memory(self, index: int, /) -> memoryview | None: ...

class Module:
    @property
    def name(self) -> str: ...
    gasLimit: float
    @property
    def gasUsed(self) -> float: ...
    @overload
    def link_function(self, module: str, name: str, function: Callable[..., Any], /) -> None: ...
    @overload
    def link_function(self, module: str, name: str, signature: str, function: Callable[..., Any], /) -> None: ...
    def link_global(self, module: str, name: str, value: WasmValue, /) -> None: ...
    def get_global(self, name: str, /) -> WasmValue: ...
    def set_global(self, name: str, value: WasmValue, /) -> None: ...

class Function:
    @property
    def name(self) -> str: ...
    @property
    def num_args(self) -> int: ...
    @property
    def num_rets(self) -> int: ...
    # wasm3's M3ValueType: 1=i32, 2=i64, 3=f32, 4=f64.
    @property
    def arg_types(self) -> tuple[int, ...]: ...
    @property
    def ret_types(self) -> tuple[int, ...]: ...
    def call_argv(self, *args: str) -> Any: ...
    def __call__(self, *args: WasmValue) -> Any: ...
